schema: ./src/schema/*.graphql
documents: ./src/app/**/*.graphql
extensions:
  nitrogql:
    generate:
      mode: with-loader-ts-5.0
      schemaOutput: ./src/generated/schema.d.ts
      schemaModuleSpecifier: "@/generated/schema"
      types:
        scalarTypes:
          Date: string